---
title: 'SQL: Joining Data'
author: "Kaymal"
output:
  github_document: default
---

Outline:

* Intro
* INNER JOIN
    + USING
    + Self-Join
    + CASE, WHEN, THEN, ELSE, and END
    + INTO
* Outer JOIN
    + LEFT JOIN
    + RIGHT JOIN
    + FULL JOIN
    + CROSS JOIN
* Set Theory
    + UNION
    + UNION ALL
    + INTERSECT
    + EXCEPT
    + Semi-Join and Anti-Join
* Subqueries (Nested Queries)
    + Inside WHERE
    + Inside SELECT
    + Inside FROM

## Introduction
```{r connect}
# Install the package in R
#install.packages("RPostgreSQL")
library(RPostgreSQL)
## Loading required package: DBI
pgdrv <- dbDriver(drvName = "PostgreSQL")

con <-DBI::dbConnect(pgdrv,
                    dbname="template1",
                    host="localhost", port=5432,
                    user = rstudioapi::askForPassword("Database username"),
                    password = rstudioapi::askForPassword("Database password"))

```

## INNER JOIN

```{sql, connection=con}
SELECT * 
FROM cities
```
```{sql, connection=con, max.print = 5}
SELECT COUNT(*) 
FROM cities
```
```{sql, connection=con}
SELECT * 
FROM countries
```

```{sql, connection=con}
SELECT cities.name AS city, countries.name AS country, countries.region 
FROM cities
  -- Inner join to countries
  INNER JOIN countries
    -- Match on the country codes
    ON cities.country_code = countries.code;
```

Get data from both the countries and economies tables to examine the inflation rate for both 2010 and 2015.

```{sql, connection=con, max.print = 5}
-- Select fields with aliases
SELECT c.code AS country_code, c.name, year, inflation_rate
FROM countries AS c
  -- Join to economies (alias e)
  INNER JOIN economies AS e
    -- Match on code
    ON c.code = e.code;
```

Get the country name, its region, and the fertility rate for both 2010 and 2015 for each country.

```{sql, connection=con, max.print = 5}
-- Select fields
SELECT c.code, c.name, c.region, p.year, fertility_rate
  -- 1. From countries (alias as c)
  FROM countries AS c
  -- 2. Join with populations (as p)
  INNER JOIN populations AS p
    -- 3. Match on country code
    ON c.code = p.country_code
```

```{sql, connection=con, max.print = 5}
-- Select fields
SELECT c.code, name, region, e.year, fertility_rate, unemployment_rate
  -- From countries (alias as c)
  FROM countries AS c
  -- Join to populations (as p)
  INNER JOIN populations AS p
    -- Match on country code
    ON c.code = p.country_code
  -- Join to economies (as e)
  INNER JOIN economies AS e
    -- Match on country code and year
    ON c.code = e.code AND e.year = p.year;
```

### USING

```{sql, connection=con, max.print = 5}
SELECT c.name AS country, continent, l.name AS language, official
  -- From countries (alias as c)
  FROM countries AS c
  -- Join to languages (as l)
  INNER JOIN languages AS l
    -- Match using code
    USING(code)
```

### Self-Join

Use the populations table to perform a self-join to calculate the percentage increase in population from 2010 to 2015 for each country code:
```{sql, connection=con, max.print = 5}
SELECT p1.country_code,
       p1.size AS size2010, 
       p2.size AS size2015,
       -- calculate growth_perc
       ((p2.size - p1.size)/p1.size * 100.0) AS growth_perc
-- From populations (alias as p1)
FROM populations AS p1
  -- Join to itself (alias as p2)
  INNER JOIN populations AS p2
    -- Match on country code
    ON p1.country_code = p2.country_code
        -- and year (with calculation)
        AND p1.year = p2.year - 5
```
### CASE, WHEN, THEN, ELSE, and END

Create a new field _geosize_group_ that groups the countries into three groups: large, medium and small.
```{sql, connection=con, max.print = 5}
SELECT name, continent, code, surface_area,
    -- First case
    CASE WHEN surface_area > 2000000 THEN 'large'
        -- Second case
        WHEN surface_area > 350000 THEN 'medium'
        -- Else clause + end
        ELSE 'small' END
        -- Alias name
        AS geosize_group
-- From table
FROM countries;
```
### INTO
Create _countries plus_ table:
```{sql, connection=con, max.print = 5}
/*
SELECT name, continent, code, surface_area,
    CASE WHEN surface_area > 2000000
            THEN 'large'
       WHEN surface_area > 350000
            THEN 'medium'
       ELSE 'small' END
       AS geosize_group
INTO countries_plus
FROM countries;
*/
```

Explore the relationship between the size of a country in terms of surface area and in terms of population using grouping fields created with CASE:

```{sql, connection=con, max.print = 5}
/*
SELECT country_code, size,
  CASE WHEN size > 50000000
            THEN 'large'
       WHEN size > 1000000
            THEN 'medium'
       ELSE 'small' END
       AS popsize_group
INTO pop_plus       
FROM populations
WHERE year = 2015;
*/

-- Select fields
SELECT name, continent, geosize_group, popsize_group
-- From countries_plus (alias as c)
FROM countries_plus AS c
  -- Join to pop_plus (alias as p)
  INNER JOIN pop_plus AS p
    -- Match on country code
    ON c.code = p.country_code
-- Order the table    
ORDER BY geosize_group;
```

## Outer JOIN

### LEFT JOIN

Begin by performing an inner join with the `cities` table on the left and the `countries` table on the right:
```{sql, connection=con, max.print = 5}
-- Select fields
SELECT c1.name AS city, code, c2.name AS country,
       region, city_proper_pop
-- From left table (with alias)
FROM cities AS c1
  -- Join to right table (with alias)
  INNER JOIN countries AS c2
    -- Match on country code
    ON c1.country_code = c2.code
-- Order by descending country code
ORDER BY code DESC;
```
Change the query to a left join, and compare the number of records:
```{sql, connection=con, max.print = 10}
SELECT c1.name AS city, code, c2.name AS country,
       region, city_proper_pop
FROM cities AS c1
  -- 1. Join right table (with alias)
  LEFT JOIN countries AS c2
    -- 2. Match on country code
    ON c1.country_code = c2.code
-- 3. Order by descending country code
ORDER BY code DESC;
```
First 6 records are not included in the first query result!

Determine the average gross domestic product (GDP) per capita by region in 2010
```{sql, connection=con}
-- Select fields
SELECT region, AVG(gdp_percapita) AS avg_gdp
-- From countries (alias as c)
FROM countries AS c
  -- Left join with economies (alias as e)
  LEFT JOIN economies AS e
    -- Match on code fields
    ON c.code = e.code
-- Focus on 2010
WHERE year = 2010
-- Group by region
GROUP BY region
-- Order by descending avg_gdp
ORDER BY avg_gdp DESC;
```

### RIGHT JOIN
Right joins aren't as common as left joins. One reason why is that you can always write a right join as a left join.

### FULL JOIN
Choose records in which region corresponds to North America or is NULL.

```{sql, connection=con, max.print = 5}
SELECT name AS country, code, region, basic_unit
-- From countries
FROM countries
  -- Join to currencies
  FULL JOIN currencies
    -- Match on code
    USING (code)
-- Where region is North America or null
WHERE region = 'North America' OR region IS NULL
-- Order by region
ORDER BY region;
```

Choose records in which countries.name starts with the capital letter 'V' or is NULL. Arrange by `countries.name` in ascending order to more clearly see the results.
```{sql, connection=con, max.print = 5}
SELECT countries.name, code, languages.name AS language
-- From languages
FROM languages
  -- Join to countries
  FULL JOIN countries
    -- Match on code
    USING (code)
-- Where countries.name starts with V or is null
WHERE countries.name LIKE 'V%' OR countries.name IS NULL
-- Order by ascending countries.name
ORDER BY countries.name;
```

### CROSS JOIN
CROSS JOINs create all possible combinations of two tables.

Explore languages potentially and most frequently spoken in the cities of Hyderabad, India and Hyderabad, Pakistan.
```{sql, connection=con, max.print = 5}
-- Select fields
SELECT c.name AS city, l.name AS language
-- From cities (alias as c)
FROM cities AS c        
  -- Join to languages (alias as l)
  CROSS JOIN languages AS l
-- Where c.name like Hyderabad
WHERE c.name LIKE 'Hyder%';
```
## Set Theory

### UNION
Duplicates are removed by using UNION.

Combine the `economies2010` and `economies2015` tables into one table.
```{sql, connection=con, max.print = 5}
-- Select fields from 2010 table
SELECT *
  -- From 2010 table
  FROM economies2010
	-- Set theory clause
	UNION
-- Select fields from 2015 table
SELECT *
  -- From 2015 table
  FROM economies2015
-- Order by code and year
ORDER BY code, year;
```

### UNION ALL
We can use `UNION ALL` to include duplicates.

Determine all combinations (include duplicates) of country code and year that exist in either the economies or the populations tables. Order by code then year.
```{sql, connection=con, max.print = 5}
-- Select fields
SELECT code, year
  -- From economies
  FROM economies
	-- Set theory clause
	UNION ALL
-- Select fields
SELECT country_code, year
  -- From populations
  FROM populations
-- Order by code, year
ORDER BY code, year;
```

### INTERSECT

Look at the records in common for country code and year for the `economies` and `populations` tables.
```{sql, connection=con, max.print = 5}
-- Select fields
SELECT code, year
  -- From economies
  FROM economies
	-- Set theory clause
	INTERSECT
-- Select fields
SELECT country_code, year
  -- From populations
  FROM populations
-- Order by code and year
ORDER BY code, year;
```

Which countries also have a city with the same name as their country name?
```{sql, connection=con, max.print = 5}
-- Select fields
SELECT name
  -- From countries
  FROM countries
	-- Set theory clause
	INTERSECT
-- Select fields
SELECT name
  -- From cities
  FROM cities;
```

### EXCEPT
We use `EXCEPT` to include only the records that are in one ttable , but not the other.

Get the names of cities in cities which are not noted as capital cities in countries as a single field result.
```{sql, connection=con, max.print = 5}
-- Select field
SELECT name
  -- From cities
  FROM cities
	-- Set theory clause
	EXCEPT
-- Select field
SELECT capital
  -- From countries
  FROM countries
-- Order by result
ORDER BY name;
```
### Semi-Joins and Anti-Joins
We use these joins in a way similar to a WHERE clause.

#### Semi-Joins
```{sql, connection=con, max.print = 5}
-- Select code
SELECT code
  -- From countries
  FROM countries
-- Where region is Middle East
WHERE region = 'Middle East';
```

```{sql, connection=con, max.print = 5}
-- Select distinct fields
SELECT DISTINCT name
  -- From languages
  FROM languages
-- Where in statement
WHERE code IN
  -- Subquery
  (SELECT code
   FROM countries
   WHERE region = 'Middle East')
-- Order by name
ORDER BY name;
```
#### Anti-Joins
Anti-join is particularly useful in identifying which records are causing an incorrect number of records to appear in join queries.


Identify the currencies used in Oceanian countries! Use an anti-join to determine which countries were not included!
```{sql, connection=con, max.print = 5}
-- Select fields
SELECT code, name
  -- From Countries
  FROM countries
  -- Where continent is Oceania
  WHERE continent = 'Oceania'
  	-- And code not in
  	AND code NOT IN
  	-- Subquery
  	(SELECT code
  	 FROM currencies);
```
## Subqueries

### Inside WHERE

Figure out which countries had high average life expectancies (at the country level) in 2015. (We want only records that were above 1.15 * 100 in terms of life expectancy for 2015)
```{sql, connection=con, max.print = 5}
-- Select fields
SELECT *
  -- From populations
  FROM populations
-- Where life_expectancy is greater than
WHERE life_expectancy >
  -- 1.15 * subquery
  1.15 * (
   SELECT AVG(life_expectancy)
   FROM populations
   WHERE year = 2015)
  AND year = 2015;
```

Get the urban area population for only capital cities.
```{sql, connection=con, max.print = 5}
-- 2. Select fields
SELECT name, country_code, urbanarea_pop
  -- 3. From cities
  FROM cities
-- 4. Where city name in the field of capital cities
WHERE name IN
  -- 1. Subquery
  (SELECT capital
   FROM countries)
ORDER BY urbanarea_pop DESC;
```

### Inside SELECT

Select the top five countries in terms of number of cities appearing in the cities table. 
```{sql, connection=con}
SELECT name AS country,
  (SELECT COUNT(*)
   FROM cities
   WHERE countries.code = cities.country_code) AS cities_num
FROM countries
ORDER BY cities_num DESC, country
LIMIT 5;
```

### Inside FROM

Determine the number of languages spoken for each country, identified by the country's local name.
```{sql, connection=con, max.print = 5}
-- Select fields
SELECT local_name, subquery.lang_num
  -- From countries
  FROM countries,
  	-- Subquery (alias as subquery)
  	(SELECT code, COUNT(*) AS lang_num
  	 FROM languages
  	 GROUP BY code) AS subquery
  -- Where codes match
  WHERE countries.code = subquery.code
-- Order by descending number of languages
ORDER BY lang_num DESC;
```
